#! /usr/bin/env bash

# Replace 8 spaces to a tab

if (($# != 2)); then
    echo "Usage: $0 <*_8spc> <*>" >& 2
    exit 1
fi

if [ ! -f $1 ]; then
    echo "File \"$1\" not found" >& 2
    exit 1
fi

if [ ! -r $1 ]; then
    echo "File \"$1\" cannot be read" >& 2
    exit 1
fi

sed 's/        /\t/g;' $1 > $2
exit 0
