#! /usr/bin/env bash

# Generate char*[] which indexes are syscall numbers 
# and values are syscall names from architecture directory

SRC=src
SC_H2ARR=sc_h2arr
SC_TBL2ARR=sc_tbl2arr
MACH_ARCH_BITS_TBL=mach_arch_bits.tbl

if (($# != 2)); then
    echo "Usage: $0 ARCH_DIR <*.c>" >& 2
    exit 1
fi

if [ ! -d $1 ]; then
    echo "Architecture directory \"$1\" not found" >& 2
    exit 1
fi

if [ ! -x $1 ]; then
    echo "Architecture directory \"$1\" cannot be execved" >& 2
    exit 1
fi

arch="#"
mach=$(uname -m)
nlines=$(wc -l < $1/${MACH_ARCH_BITS_TBL})

for ((i=1; i<=nlines; i++)); do
    items=($(sed -n "${i}p;" $1/${MACH_ARCH_BITS_TBL}))
    if [ ${items[0]} == ${mach} ]; then
        arch=${items[1]}
        bits=${items[2]}
        break
    fi
done

if [ ${arch} == "#" ]; then
    echo "Machine ${mach} not found" >& 2
    exit 1
fi

if [ -f $1/sctblsrc_${arch}_${bits}.tbl ]; then
    bash ${SRC}/${SC_TBL2ARR} $1/sctblsrc_${arch}_${bits}.tbl $2
    exit 0
fi

if [ -f $1/sctblsrc_${arch}_${bits}.h ]; then
    bash ${SRC}/${SC_H2ARR} $1/sctblsrc_${arch}_${bits}.h $2
    exit 0
fi

echo "Table $1/sctblsrc_${arch}_${bits}.tbl or header $1/sctblsrc_${arch}_${bits}.h not found" >& 2
exit 1
