#! /usr/bin/env bash

# Convert syscall table to char*[] which indexes
# are syscall numbers and values are syscall names

if (($# != 2)); then
    echo "Usage: $0 <*.tbl> <*.c>" >& 2
    exit 1
fi

TBL="$1"
CFILE="$2"

if [ ! -f "${TBL}" ]; then
    echo "Table \"${TBL}\" not found" >& 2
    exit 1
fi

if [ ! -r "${TBL}" ]; then
    echo "Table \"${TBL}\" cannot be read" >& 2
    exit 1
fi

sed 's/#.*//;/^\s*$/d;' "${TBL}" > "${CFILE}.tmp"
echo "char* scname[#] = {" > "${CFILE}"
pwn=0
nlines=$(wc -l < "${CFILE}.tmp")

for ((i=1; i<=nlines; i++)); do
    items=($(sed -n "${i}p;" "${CFILE}.tmp"))
    while [ ${pwn} != ${items[0]} ]; do
        echo -e "\t0," >> "${CFILE}"
        ((pwn++))
    done
    echo -e "\t\"${items[2]}\"," >> "${CFILE}"
    ((pwn++))
    if ((i == nlines)); then
        sed -i "1s/#/${pwn}/;$((${pwn} + 1))s/,\$//;" "${CFILE}"
    fi
done

echo "};" >> "${CFILE}"
rm "${CFILE}.tmp"
echo ${pwn}
exit 0
